---
- name: installing pkgs
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
    - httpd
    - java
    - my-sql
      # - epel

- name: epel-release
  shell: amazon-linux-extras install epel -y

- name: Extract tomcat 8
  ansible.builtin.unarchive:
    src: "{{TC_url}}"
    dest: /mnt/
    remote_src: yes

- name: student file
  ansible.builtin.get_url:
    url: "{{S3_bkt}}"
    dest: "{{TC_Dir}}/webapps/"

- name: jdbc connector
  ansible.builtin.copy:
    src: files/mysql-connector.jar.j2
    dest: "{{TC_Dir}}/lib/mysql-connector.jar"

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: templates/context.xml
    dest: "{{TC_Dir}}/conf/context.xml"

# - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
#   ansible.posix.seboolean:
#     name: httpd_can_network_connect
#     state: yes
#     persistent: yes

    # temperary start
    #- name : start tomcat
    # shell: sh {{TC_Dir}}/bin/catalina.sh start

    #permanent start
- name : tomcat daemons
  copy:
    src: files/tomcat-init
    dest: /etc/init.d/tomcat
    mode: 0755

- name: daemon reload
  shell: systemctl daemon-reload

- name: start tomcat
  service:
    name: tomcat
    state: started
    enabled: true
