---
- name: installing pkgs
  package:
    name: httpd
    state: present

- name: moving proxy file 
  ansible.builtin.copy:
    src: files/proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf

- name: moving proxy file 
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html 

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started
